### ISSUE TITLE
Add null check ?

### ISSUE THREAD

**Issue by LiangNex** [dolymood/webpack-transform-modules-plugin#6]
I am suffering below issue while switching package manager from yarn to npm.

```
ERROR  Cannot read property 'modulePath' of null                    
 at Object.collectTransformModules (node_modules/webpack-transform-modules-plugin/lib/util.js:25:20)
 at TransformModulesPlugin._collectTransformModules (node_modules/webpack-transform-modules-plugin/lib/index.js:151:8)
 at runGetter (node_modules/webpack-transform-modules-plugin/lib/index.js:22:33)
 at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
 at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
 at Compiler.run (node_modules/webpack/lib/Compiler.js:265:24)
 at Promise (node_modules/@nuxt/webpack/dist/webpack.js:5110:18)
```

It might be some dependencies which are not installed correctly and I had got it fixed by redo the installation.

Perhaps we can apply a null check there?

**Comment by dolymood** [comment]
If we can not resolve some module, maybe have an error is better

**Comment by LiangNex** [comment]
ok thanks, maybe post the stack trace here when I met it. close for now
